; PlatformIO Project Configuration File
; ระบบตรวจสอบไฟฟ้าดับ ESP32 + WeLPRU Notification API

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder, time

lib_deps =
    bblanchon/ArduinoJson@^7.0.4

build_flags =
    -D CORE_DEBUG_LEVEL=3
